### ISSUE TITLE
docker getting-start

### ISSUE THREAD

**Issue by mrbone** [mrbone/mrbone.github.io#85]
# docker 知识点

[TOC]

## container

container 是一个运行中的 image 实例。  
可以通过 `docker ps` 查看所有运行中的 container。

## image
image 是一个可执行的程序 package，包括程序所需要的所有的`依赖/环境变量/库/配置文件`

## docker 方式的 app

层级： container - service - stack

## Dockerfile

Dockerfile 是当前 app 下 docker 依赖的描述，类似于 node 的 `package.json`，不过其更像一个脚本文件。当使用 `docker build` 时，会按照 Dockerfile 的步骤去构建 image。

```
# Use an official Python runtime as a parent image
FROM python:2.7-slim

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
ADD . /app

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME World

# Run app.py when the container launches
CMD ["python", "app.py"]
```

建立 `requirements.txt` 和 `app.py`。

再将 app 构建为 docker image。

```
docker build -t friendlyhello .
```
我们再使用 `docker image ls` 就能看到一个 tag 为 `friendlyhello` 的 image 在列表中了。

## docker run -p 
上面的例子向外部暴露 80 端口，在 run 的时候可以通过 `outPort:containerPort` 映射

## docker push 
- 在 docker hub 上注册帐号
- 命令行中 `docker login` 登录
- `docker tag imageName username/repo:tag`
- `docker push username/repo:tag`
 
## service
在分布式应用中，应用的不同部分被叫做 `service`。

## docker compose
docker-compose 是一个可以同时运行多个 container 的 docker 程序。  
`docker-compose.yml` 是一个定义了 docker containers 在产品环境行为的 yml 文件。  
示例如下：

```
version: "3"
services:
  web:
    image: mrbone/get-start:part-2
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:
```
这个 yml 文件告诉 docker 做如下步骤
1. pull mrbone/get-start:part-2
2. 启动 5 个该 image 的实例并取名 `web`，并限制每个实例最高 10% cpu 使用量(所有核心)和 50mb 内存。
3. 重启策略: 如果有一个实例报错，则重启 containers。
4. 映射宿主机器的 80 端口到 `web` 的 80 端口。
5. `web` 的 containers 使用 `webnet` 共享宿主的 80 端口做负载均衡。(在 `web` 内部短暂的发布到 80 端口)
6. 定义 `webnet` 作为默认 network 的默认设置。

- 接着使用 `docker swarm init` 初始化。  
- 运行 `docker stack deploy -c docker-compose.yml anyname`。  
- 之后再用 `docker service ls` 查看。
- 使用 `curl -4 http://localhost` 查看响应。

当发起多次请求后，我们会发现响应的 hostname 会变化，这是应为该 swarm 做了负载均衡。

并且我们修改了 `docker-compose.yml` 之后需要再运行一次 `docker stack deploy -c docker-comopose.yml` 就行。并不需要 stop 运行中的 stack。

## swarm 和 cluster
- cluster - 集群  
- 多个应用通过 `dockersized` 合并到多台机器上称为 __swarm__

### 理解
- __swarm__ 是一组运行 docker 并且合并为一个集群的机器。  
- docker 通过 `swarm manager` 操作 swarm。  
- 在 swarm 中的机器可以是物理机，也可以是虚拟机。但是只要属于 swarm，那么所有机器被叫做 __nodes__
- __swarm manager__ 是 swarm 中唯一能够执行用户命令、或者授权其他机器以 __worker__ 加入 swarm 的机器。
- __workers__ 只提供算力，没有和其他机器通信的权限。
 

## docker swarm mode
`docker swarm init` 是开启 docker swarm 模式的命令，此命令会把当前机器转换为 swarm manager。之后在其他机器上运行 `docker swarm join` 就可以把他们以 __worker__ 形式加入到 swarm 中。
